# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Expenser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Expenser
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'Charts'

  target 'ExpenserTests' do
    inherit! :search_paths
   pod 'Quick'
   pod 'Nimble'  
  end

  target 'ExpenserUITests' do
    # Pods for testing
  end
end
